# Server
server.port=8080

# MySQL DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/iot_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Linh123@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# MQTT Broker
mqtt.broker.url=tcp://localhost:1884
mqtt.broker.username=PhamMaiLinh
mqtt.broker.password=B23DCCN488
mqtt.client.id=SpringBoot_IoT_Client
mqtt.topic.sensor=iot/data_sensor
mqtt.topic.control=iot/devices_control
mqtt.topic.status=iot/devices_status

# CORS
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

# Logging
logging.level.com.ptit.iot=DEBUG
